{
  "openapi": "3.0.0",
  "info": {
    "description": "\r\n# About\r\n\r\nConsents is a CRUD API and Data Store which is used for storage and retrieval of customers' consents to access their financial data.\r\n\r\n# Authentication\r\nTo utilise the Consent Service, a bearer token must be issued along with the request.  \r\n\r\nDetails on how to obtain a bearer token, and how to utilise it as part of the request are detailed in the [Runpath Platform Authentication Guide](/document/PlatformAuthentication).\r\nTo obtain an access token, follow the instructions in the Platform Authentication guide and add the following scopes:  \r\n<br/>\r\nScopes   | \r\n------------- | \r\nconsent.read |\t\r\nconsent.readwrite |\t\r\n",
    "title": "Runpath.Consents",
    "version": "1.0"
  },
  "servers": [
    {
      "url": "https://cat.consent.runpath.com/"
    }
  ],
  "paths": {
    "/consents": {
      "post": {
        "responses": {
          "201": {
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Consent"
                }
              },
              "text/json": {
                "schema": {
                  "$ref": "#/components/schemas/Consent"
                }
              }
            },
            "description": "Created"
          },
          "400": {
            "description": "BadRequest"
          },
          "401": {
            "description": "Unauthorized"
          },
          "403": {
            "description": "Forbidden"
          },
          "404": {
            "description": "Not Found"
          },
          "422": {
            "description": "Unprocessable Entity"
          },
          "500": {
            "description": "Internal Server Error"
          }
        },
        "tags": [
          "Consents"
        ],
        "operationId": "Consents_Create",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/Consent"
              }
            },
            "text/json": {
              "schema": {
                "$ref": "#/components/schemas/Consent"
              }
            }
          },
          "description": "The new consent to save.",
          "required": true
        },
        "summary": "Saves a new consent into the consent store."
      }
    },
    "/consents/{consentId}/revoke": {
      "post": {
        "parameters": [
          {
            "description": "The consent identifier.",
            "in": "path",
            "name": "consentId",
            "required": true,
            "schema": {
              "format": "int32",
              "type": "integer"
            }
          }
        ],
        "responses": {
          "200": {
            "content": {
              "application/json": {
                "schema": {
                  "type": "object"
                }
              },
              "text/json": {
                "schema": {
                  "type": "object"
                }
              }
            },
            "description": "OK"
          },
          "204": {
            "description": "NoContent"
          },
          "401": {
            "description": "Unauthorized"
          },
          "403": {
            "description": "Forbidden"
          },
          "404": {
            "description": "Not Found"
          },
          "422": {
            "description": "Unprocessable Entity"
          },
          "500": {
            "description": "Internal Server Error"
          }
        },
        "tags": [
          "Consents"
        ],
        "operationId": "Consents_RevokeConsent",
        "summary": "Revokes the consent."
      }
    },
    "/consents/{id}": {
      "get": {
        "parameters": [
          {
            "description": "The unique id of the consent to get.",
            "in": "path",
            "name": "id",
            "required": true,
            "schema": {
              "format": "int32",
              "type": "integer"
            }
          }
        ],
        "responses": {
          "200": {
            "content": {
              "application/json": {
                "examples": {
                  "response": {
                    "value": {
                      "date": "2018-09-10T22:11:47.2272027+00:00",
                      "duration": "Transaction",
                      "expirationDate": "2019-01-08T22:11:47.2272027+00:00",
                      "externalId": "xoRSVjqllKZP",
                      "id": 569552,
                      "mechanism": "Website",
                      "participants": [
                        {
                          "assetIdentifiers": [
                            {
                              "name": "AccountId",
                              "value": "69854225"
                            }
                          ],
                          "name": "LoremBank",
                          "type": "DataProvider"
                        }
                      ],
                      "partyId": 698566,
                      "serviceId": 256985,
                      "status": "Active"
                    }
                  }
                },
                "schema": {
                  "$ref": "#/components/schemas/Consent"
                }
              },
              "text/json": {
                "schema": {
                  "$ref": "#/components/schemas/Consent"
                }
              }
            },
            "description": "OK"
          },
          "401": {
            "description": "Unauthorized"
          },
          "403": {
            "description": "Forbidden"
          },
          "404": {
            "description": "Not Found"
          },
          "500": {
            "description": "Internal Server Error"
          }
        },
        "tags": [
          "Consents"
        ],
        "operationId": "Consents_GetById",
        "summary": "Gets an individual consent by it's unique id."
      },
      "put": {
        "parameters": [
          {
            "description": "The unique id of the consent to update",
            "in": "path",
            "name": "id",
            "required": true,
            "schema": {
              "format": "int32",
              "type": "integer"
            }
          }
        ],
        "responses": {
          "200": {
            "content": {
              "application/json": {
                "examples": {
                  "response": {
                    "value": {
                      "date": "2018-09-10T22:11:47.2428576+00:00",
                      "duration": "Transaction",
                      "expirationDate": "2019-01-08T22:11:47.2428576+00:00",
                      "externalId": "xoRSVjqllKZP",
                      "id": 569552,
                      "mechanism": "Website",
                      "participants": [
                        {
                          "assetIdentifiers": [
                            {
                              "name": "AccountId",
                              "value": "69854225"
                            }
                          ],
                          "name": "LoremBank",
                          "type": "DataProvider"
                        }
                      ],
                      "partyId": 698566,
                      "serviceId": 256985,
                      "status": "Active"
                    }
                  }
                },
                "schema": {
                  "type": "object"
                }
              },
              "text/json": {
                "schema": {
                  "type": "object"
                }
              }
            },
            "description": "OK"
          },
          "201": {
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Consent"
                }
              },
              "text/json": {
                "schema": {
                  "$ref": "#/components/schemas/Consent"
                }
              }
            },
            "description": "Created"
          },
          "400": {
            "description": "BadRequest"
          },
          "401": {
            "description": "Unauthorized"
          },
          "403": {
            "description": "Forbidden"
          },
          "404": {
            "description": "Not Found"
          },
          "422": {
            "description": "Unprocessable Entity"
          },
          "500": {
            "description": "Internal Server Error"
          }
        },
        "tags": [
          "Consents"
        ],
        "operationId": "Consents_Update",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/Consent"
              }
            },
            "text/json": {
              "schema": {
                "$ref": "#/components/schemas/Consent"
              }
            }
          },
          "description": "The new consent details. These will override the consent details in the store",
          "required": true
        },
        "summary": "Updates an existing consent in the consent store."
      }
    },
    "/parties/{id}/consents": {
      "get": {
        "parameters": [
          {
            "description": "The unique id of the party.",
            "in": "path",
            "name": "id",
            "required": true,
            "schema": {
              "format": "int32",
              "type": "integer"
            }
          }
        ],
        "responses": {
          "200": {
            "content": {
              "application/json": {
                "examples": {
                  "response": {
                    "value": [
                      {
                        "date": "2018-09-10T22:11:47.258491+00:00",
                        "duration": "Transaction",
                        "expirationDate": "2019-01-08T22:11:47.258491+00:00",
                        "externalId": "xoRSVjqllKZP",
                        "id": 569552,
                        "mechanism": "Website",
                        "participants": [
                          {
                            "assetIdentifiers": [
                              {
                                "name": "AccountId",
                                "value": "69854225"
                              }
                            ],
                            "name": "LoremBank",
                            "type": "DataProvider"
                          }
                        ],
                        "partyId": 698566,
                        "serviceId": 256985,
                        "status": "Active"
                      }
                    ]
                  }
                },
                "schema": {
                  "items": {
                    "$ref": "#/components/schemas/Consent"
                  },
                  "type": "array"
                }
              },
              "text/json": {
                "schema": {
                  "items": {
                    "$ref": "#/components/schemas/Consent"
                  },
                  "type": "array"
                }
              }
            },
            "description": "OK"
          },
          "401": {
            "description": "Unauthorized"
          },
          "403": {
            "description": "Forbidden"
          },
          "404": {
            "description": "Not Found"
          },
          "500": {
            "description": "Internal Server Error"
          }
        },
        "tags": [
          "Parties"
        ],
        "operationId": "Parties_GetConsentsByPartyId",
        "summary": "Gets the consents associated with the party"
      }
    },
    "/partners/{partnerId}/consents": {
      "get": {
        "parameters": [
          {
            "description": "The partner identifier.",
            "in": "path",
            "name": "partnerId",
            "required": true,
            "schema": {
              "format": "int32",
              "type": "integer"
            }
          },
          {
            "description": "The expiration date.",
            "in": "query",
            "name": "expirationDate",
            "required": true,
            "schema": {
              "format": "date-time",
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "content": {
              "application/json": {
                "schema": {
                  "items": {
                    "$ref": "#/components/schemas/Consent"
                  },
                  "type": "array"
                }
              },
              "text/json": {
                "schema": {
                  "items": {
                    "$ref": "#/components/schemas/Consent"
                  },
                  "type": "array"
                }
              }
            },
            "description": "OK"
          },
          "401": {
            "description": "Unauthorized"
          },
          "403": {
            "description": "Forbidden"
          },
          "404": {
            "description": "Not Found"
          },
          "500": {
            "description": "Internal Server Error"
          }
        },
        "tags": [
          "Partner"
        ],
        "operationId": "Partner_GetConsentsAboutToExpire",
        "summary": "Gets the consents about to expire for a given partner"
      }
    },
    "/services/{id}/consents": {
      "get": {
        "parameters": [
          {
            "description": "The unique id of the service",
            "in": "path",
            "name": "id",
            "required": true,
            "schema": {
              "format": "int32",
              "type": "integer"
            }
          }
        ],
        "responses": {
          "200": {
            "content": {
              "application/json": {
                "examples": {
                  "response": {
                    "value": [
                      {
                        "date": "2018-09-10T22:11:47.2741102+00:00",
                        "duration": "Transaction",
                        "expirationDate": "2019-01-08T22:11:47.2741102+00:00",
                        "externalId": "xoRSVjqllKZP",
                        "id": 569552,
                        "mechanism": "Website",
                        "participants": [
                          {
                            "assetIdentifiers": [
                              {
                                "name": "AccountId",
                                "value": "69854225"
                              }
                            ],
                            "name": "LoremBank",
                            "type": "DataProvider"
                          }
                        ],
                        "partyId": 698566,
                        "serviceId": 256985,
                        "status": "Active"
                      }
                    ]
                  }
                },
                "schema": {
                  "items": {
                    "$ref": "#/components/schemas/Consent"
                  },
                  "type": "array"
                }
              },
              "text/json": {
                "schema": {
                  "items": {
                    "$ref": "#/components/schemas/Consent"
                  },
                  "type": "array"
                }
              }
            },
            "description": "OK"
          },
          "401": {
            "description": "Unauthorized"
          },
          "403": {
            "description": "Forbidden"
          },
          "404": {
            "description": "Not Found"
          },
          "500": {
            "description": "Internal Server Error"
          }
        },
        "tags": [
          "Services"
        ],
        "operationId": "Services_GetConsentsByServiceId",
        "summary": "Gets the latest consent for the given service"
      }
    }
  },
  "components": {
    "schemas": {
      "AssetIdentifiers": {
        "description": "Asset Identifiers",
        "properties": {
          "name": {
            "description": "Name of identifier",
            "maxLength": 50,
            "minLength": 0,
            "type": "string"
          },
          "value": {
            "description": "Value of Identifier",
            "maxLength": 50,
            "minLength": 0,
            "type": "string"
          }
        },
        "type": "object"
      },
      "Consent": {
        "description": "The main consent model",
        "example": {
          "date": "2018-09-10T22:11:47.2428576+00:00",
          "duration": "Transaction",
          "expirationDate": "2019-01-08T22:11:47.2428576+00:00",
          "externalId": "xoRSVjqllKZP",
          "id": 569552,
          "mechanism": "Website",
          "participants": [
            {
              "assetIdentifiers": [
                {
                  "name": "AccountId",
                  "value": "69854225"
                }
              ],
              "name": "LoremBank",
              "type": "DataProvider"
            }
          ],
          "partyId": 698566,
          "serviceId": 256985,
          "status": "Active"
        },
        "properties": {
          "date": {
            "description": "Date of Consent",
            "example": "2018-10-10T22:11:46.7584939+00:00",
            "format": "date-time",
            "type": "string"
          },
          "duration": {
            "description": "Duration of consent",
            "enum": [
              "Transaction",
              "FixedPeriod"
            ],
            "type": "string"
          },
          "expirationDate": {
            "description": "Date of consent expiry",
            "example": "2018-10-10T22:11:46.7741094+00:00",
            "format": "date-time",
            "type": "string"
          },
          "externalId": {
            "description": "Any relevant third party to be stored against the consent",
            "maxLength": 100,
            "minLength": 0,
            "type": "string"
          },
          "id": {
            "description": "The Unique identifier for each consent",
            "format": "int32",
            "type": "integer"
          },
          "mechanism": {
            "description": "Entity where the consent has been granted",
            "enum": [
              "Website",
              "App",
              "Email",
              "Telephone",
              "Letter"
            ],
            "type": "string"
          },
          "participants": {
            "description": "List of participants associated with the consent",
            "items": {
              "$ref": "#/components/schemas/Participants"
            },
            "type": "array"
          },
          "partyId": {
            "description": "Party Id",
            "format": "int32",
            "type": "integer"
          },
          "serviceId": {
            "description": "Id of service calling the service",
            "format": "int32",
            "type": "integer"
          },
          "status": {
            "description": "Status of consent. Active | Revoked | Rejected",
            "enum": [
              "Active",
              "Awaiting",
              "Revoked",
              "Rejected",
              "Expired"
            ],
            "type": "string"
          }
        },
        "required": [
          "date",
          "mechanism",
          "duration",
          "expirationDate",
          "status",
          "partyId",
          "serviceId"
        ],
        "type": "object"
      },
      "Participants": {
        "description": "Parties related to a consent",
        "properties": {
          "assetIdentifiers": {
            "description": "List of identifiers for the party",
            "items": {
              "$ref": "#/components/schemas/AssetIdentifiers"
            },
            "type": "array"
          },
          "name": {
            "description": "Name of participant",
            "maxLength": 50,
            "minLength": 0,
            "type": "string"
          },
          "type": {
            "description": "Type of participant. DataController | DataProcessor | DataProvider",
            "enum": [
              "DataController",
              "DataProcessor",
              "DataProvider"
            ],
            "type": "string"
          }
        },
        "type": "object"
      }
    }
  }
}
