{
  "swagger": "2.0",
  "info": {
    "version": "1.0",
    "title": "Runpath.Consents",
    "description": "\r\n# About\r\n\r\nConsents is a CRUD API and Data Store which is used for storage and retrieval of customers' consents to access their financial data.\r\n\r\n# Authentication\r\nTo utilise the Consent Service, a bearer token must be issued along with the request.  \r\n\r\nDetails on how to obtain a bearer token, and how to utilise it as part of the request are detailed in the [Runpath Platform Authentication Guide](/document/PlatformAuthentication).\r\nTo obtain an access token, follow the instructions in the Platform Authentication guide and add the following scopes:  \r\n<br/>\r\nScopes   | \r\n------------- | \r\nconsent.read |\t\r\nconsent.readwrite |\t\r\n"
  },
  "host": "cat.consent.runpath.com",
  "schemes": [
    "https"
  ],
  "paths": {
    "/consents": {
      "post": {
        "tags": [
          "Consents"
        ],
        "summary": "Saves a new consent into the consent store.",
        "operationId": "Consents_Create",
        "consumes": [
          "application/json",
          "text/json"
        ],
        "produces": [
          "application/json",
          "text/json"
        ],
        "parameters": [
          {
            "name": "consent",
            "in": "body",
            "description": "The new consent to save.",
            "required": true,
            "schema": {
              "$ref": "#/definitions/Consent"
            }
          }
        ],
        "responses": {
          "201": {
            "description": "Created",
            "schema": {
              "$ref": "#/definitions/Consent"
            }
          },
          "400": {
            "description": "BadRequest"
          },
          "401": {
            "description": "Unauthorized"
          },
          "403": {
            "description": "Forbidden"
          },
          "404": {
            "description": "Not Found"
          },
          "422": {
            "description": "Unprocessable Entity"
          },
          "500": {
            "description": "Internal Server Error"
          }
        }
      }
    },
    "/consents/{id}": {
      "get": {
        "tags": [
          "Consents"
        ],
        "summary": "Gets an individual consent by it's unique id.",
        "operationId": "Consents_GetById",
        "consumes": [],
        "produces": [
          "application/json",
          "text/json"
        ],
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "description": "The unique id of the consent to get.",
            "required": true,
            "type": "integer",
            "format": "int32"
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "$ref": "#/definitions/Consent"
            },
            "examples": {
              "application/json": {
                "id": 569552,
                "date": "2018-09-10T22:11:47.2272027+00:00",
                "mechanism": "Website",
                "duration": "Transaction",
                "expirationDate": "2019-01-08T22:11:47.2272027+00:00",
                "status": "Active",
                "partyId": 698566,
                "serviceId": 256985,
                "externalId": "xoRSVjqllKZP",
                "participants": [
                  {
                    "type": "DataProvider",
                    "name": "LoremBank",
                    "assetIdentifiers": [
                      {
                        "name": "AccountId",
                        "value": "69854225"
                      }
                    ]
                  }
                ]
              }
            }
          },
          "401": {
            "description": "Unauthorized"
          },
          "403": {
            "description": "Forbidden"
          },
          "404": {
            "description": "Not Found"
          },
          "500": {
            "description": "Internal Server Error"
          }
        }
      },
      "put": {
        "tags": [
          "Consents"
        ],
        "summary": "Updates an existing consent in the consent store.",
        "operationId": "Consents_Update",
        "consumes": [
          "application/json",
          "text/json"
        ],
        "produces": [
          "application/json",
          "text/json"
        ],
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "description": "The unique id of the consent to update",
            "required": true,
            "type": "integer",
            "format": "int32"
          },
          {
            "name": "consent",
            "in": "body",
            "description": "The new consent details. These will override the consent details in the store",
            "required": true,
            "schema": {
              "$ref": "#/definitions/Consent"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "type": "object"
            },
            "examples": {
              "application/json": {
                "id": 569552,
                "date": "2018-09-10T22:11:47.2428576+00:00",
                "mechanism": "Website",
                "duration": "Transaction",
                "expirationDate": "2019-01-08T22:11:47.2428576+00:00",
                "status": "Active",
                "partyId": 698566,
                "serviceId": 256985,
                "externalId": "xoRSVjqllKZP",
                "participants": [
                  {
                    "type": "DataProvider",
                    "name": "LoremBank",
                    "assetIdentifiers": [
                      {
                        "name": "AccountId",
                        "value": "69854225"
                      }
                    ]
                  }
                ]
              }
            }
          },
          "201": {
            "description": "Created",
            "schema": {
              "$ref": "#/definitions/Consent"
            }
          },
          "400": {
            "description": "BadRequest"
          },
          "401": {
            "description": "Unauthorized"
          },
          "403": {
            "description": "Forbidden"
          },
          "404": {
            "description": "Not Found"
          },
          "422": {
            "description": "Unprocessable Entity"
          },
          "500": {
            "description": "Internal Server Error"
          }
        }
      }
    },
    "/consents/{consentId}/revoke": {
      "post": {
        "tags": [
          "Consents"
        ],
        "summary": "Revokes the consent.",
        "operationId": "Consents_RevokeConsent",
        "consumes": [],
        "produces": [
          "application/json",
          "text/json"
        ],
        "parameters": [
          {
            "name": "consentId",
            "in": "path",
            "description": "The consent identifier.",
            "required": true,
            "type": "integer",
            "format": "int32"
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "type": "object"
            }
          },
          "204": {
            "description": "NoContent"
          },
          "401": {
            "description": "Unauthorized"
          },
          "403": {
            "description": "Forbidden"
          },
          "404": {
            "description": "Not Found"
          },
          "422": {
            "description": "Unprocessable Entity"
          },
          "500": {
            "description": "Internal Server Error"
          }
        }
      }
    },
    "/parties/{id}/consents": {
      "get": {
        "tags": [
          "Parties"
        ],
        "summary": "Gets the consents associated with the party",
        "operationId": "Parties_GetConsentsByPartyId",
        "consumes": [],
        "produces": [
          "application/json",
          "text/json"
        ],
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "description": "The unique id of the party.",
            "required": true,
            "type": "integer",
            "format": "int32"
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/Consent"
              }
            },
            "examples": {
              "application/json": [
                {
                  "id": 569552,
                  "date": "2018-09-10T22:11:47.258491+00:00",
                  "mechanism": "Website",
                  "duration": "Transaction",
                  "expirationDate": "2019-01-08T22:11:47.258491+00:00",
                  "status": "Active",
                  "partyId": 698566,
                  "serviceId": 256985,
                  "externalId": "xoRSVjqllKZP",
                  "participants": [
                    {
                      "type": "DataProvider",
                      "name": "LoremBank",
                      "assetIdentifiers": [
                        {
                          "name": "AccountId",
                          "value": "69854225"
                        }
                      ]
                    }
                  ]
                }
              ]
            }
          },
          "401": {
            "description": "Unauthorized"
          },
          "403": {
            "description": "Forbidden"
          },
          "404": {
            "description": "Not Found"
          },
          "500": {
            "description": "Internal Server Error"
          }
        }
      }
    },
    "/partners/{partnerId}/consents": {
      "get": {
        "tags": [
          "Partner"
        ],
        "summary": "Gets the consents about to expire for a given partner",
        "operationId": "Partner_GetConsentsAboutToExpire",
        "consumes": [],
        "produces": [
          "application/json",
          "text/json"
        ],
        "parameters": [
          {
            "name": "partnerId",
            "in": "path",
            "description": "The partner identifier.",
            "required": true,
            "type": "integer",
            "format": "int32"
          },
          {
            "name": "expirationDate",
            "in": "query",
            "description": "The expiration date.",
            "required": true,
            "type": "string",
            "format": "date-time"
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/Consent"
              }
            }
          },
          "401": {
            "description": "Unauthorized"
          },
          "403": {
            "description": "Forbidden"
          },
          "404": {
            "description": "Not Found"
          },
          "500": {
            "description": "Internal Server Error"
          }
        }
      }
    },
    "/services/{id}/consents": {
      "get": {
        "tags": [
          "Services"
        ],
        "summary": "Gets the latest consent for the given service",
        "operationId": "Services_GetConsentsByServiceId",
        "consumes": [],
        "produces": [
          "application/json",
          "text/json"
        ],
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "description": "The unique id of the service",
            "required": true,
            "type": "integer",
            "format": "int32"
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/Consent"
              }
            },
            "examples": {
              "application/json": [
                {
                  "id": 569552,
                  "date": "2018-09-10T22:11:47.2741102+00:00",
                  "mechanism": "Website",
                  "duration": "Transaction",
                  "expirationDate": "2019-01-08T22:11:47.2741102+00:00",
                  "status": "Active",
                  "partyId": 698566,
                  "serviceId": 256985,
                  "externalId": "xoRSVjqllKZP",
                  "participants": [
                    {
                      "type": "DataProvider",
                      "name": "LoremBank",
                      "assetIdentifiers": [
                        {
                          "name": "AccountId",
                          "value": "69854225"
                        }
                      ]
                    }
                  ]
                }
              ]
            }
          },
          "401": {
            "description": "Unauthorized"
          },
          "403": {
            "description": "Forbidden"
          },
          "404": {
            "description": "Not Found"
          },
          "500": {
            "description": "Internal Server Error"
          }
        }
      }
    }
  },
  "definitions": {
    "Consent": {
      "description": "The main consent model",
      "required": [
        "date",
        "mechanism",
        "duration",
        "expirationDate",
        "status",
        "partyId",
        "serviceId"
      ],
      "type": "object",
      "properties": {
        "id": {
          "format": "int32",
          "description": "The Unique identifier for each consent",
          "type": "integer"
        },
        "date": {
          "format": "date-time",
          "description": "Date of Consent",
          "type": "string",
          "example": "2018-10-10T22:11:46.7584939+00:00"
        },
        "mechanism": {
          "description": "Entity where the consent has been granted",
          "enum": [
            "Website",
            "App",
            "Email",
            "Telephone",
            "Letter"
          ],
          "type": "string"
        },
        "duration": {
          "description": "Duration of consent",
          "enum": [
            "Transaction",
            "FixedPeriod"
          ],
          "type": "string"
        },
        "expirationDate": {
          "format": "date-time",
          "description": "Date of consent expiry",
          "type": "string",
          "example": "2018-10-10T22:11:46.7741094+00:00"
        },
        "status": {
          "description": "Status of consent. Active | Revoked | Rejected",
          "enum": [
            "Active",
            "Awaiting",
            "Revoked",
            "Rejected",
            "Expired"
          ],
          "type": "string"
        },
        "partyId": {
          "format": "int32",
          "description": "Party Id",
          "type": "integer"
        },
        "serviceId": {
          "format": "int32",
          "description": "Id of service calling the service",
          "type": "integer"
        },
        "externalId": {
          "description": "Any relevant third party to be stored against the consent",
          "maxLength": 100,
          "minLength": 0,
          "type": "string"
        },
        "participants": {
          "description": "List of participants associated with the consent",
          "type": "array",
          "items": {
            "$ref": "#/definitions/Participants"
          }
        }
      },
      "example": {
        "id": 569552,
        "date": "2018-09-10T22:11:47.2428576+00:00",
        "mechanism": "Website",
        "duration": "Transaction",
        "expirationDate": "2019-01-08T22:11:47.2428576+00:00",
        "status": "Active",
        "partyId": 698566,
        "serviceId": 256985,
        "externalId": "xoRSVjqllKZP",
        "participants": [
          {
            "type": "DataProvider",
            "name": "LoremBank",
            "assetIdentifiers": [
              {
                "name": "AccountId",
                "value": "69854225"
              }
            ]
          }
        ]
      }
    },
    "Participants": {
      "description": "Parties related to a consent",
      "type": "object",
      "properties": {
        "type": {
          "description": "Type of participant. DataController | DataProcessor | DataProvider",
          "enum": [
            "DataController",
            "DataProcessor",
            "DataProvider"
          ],
          "type": "string"
        },
        "name": {
          "description": "Name of participant",
          "maxLength": 50,
          "minLength": 0,
          "type": "string"
        },
        "assetIdentifiers": {
          "description": "List of identifiers for the party",
          "type": "array",
          "items": {
            "$ref": "#/definitions/AssetIdentifiers"
          }
        }
      }
    },
    "AssetIdentifiers": {
      "description": "Asset Identifiers",
      "type": "object",
      "properties": {
        "name": {
          "description": "Name of identifier",
          "maxLength": 50,
          "minLength": 0,
          "type": "string"
        },
        "value": {
          "description": "Value of Identifier",
          "maxLength": 50,
          "minLength": 0,
          "type": "string"
        }
      }
    }
  }
}