{
  "openapi": "3.0.0",
  "info": {
    "description": "A service for storing transactions, categorisations and metrics\r\n# About\r\nThe Transaction Service is used for storage and retrieval of Customer Transaction data from a variety of third-party sources, provided in a single consistent transaction format.  As well as describing the API Calls available to retrieve Transactions, this specification also describes additional information about additional fields containing enriched and cleansed data for Categories and Descriptions.\r\n\r\n\r\n\r\n# Authentication\r\nTo utilise the Transaction Service, a bearer token must be issued along with the request.  \r\n\r\nDetails on how to obtain a bearer token, and how to utilise it as part of the request are detailed in the [Runpath Platform Authentication Guide](/document/PlatformAuthentication).\r\nTo obtain an access token, follow the instructions in the Platform Authentication guide and add the following scopes:  \r\n<br/>\r\nScopes   | \r\n------------- | \r\ntransactions.read |\t\r\ntransactions.readwrite |\t\r\n\r\n\r\n\r\n# Data Enrichment\r\n## Bank Code Mappings\r\n _The Transactions Model Contains a **codes** property containing transaction code mappings.  This section provides more information about this._ \r\n\r\n\r\nThe Open Banking Standard provides transaction data with two transaction code types:  A proprietary\r\ntransaction code, used by a **specific banking institution**, and also a standard transaction code defined by\r\nthe Open Banking Specification (ISO 20022 - the Universal financial industry message scheme). For example:\r\n```javascript\r\n    \"BankTransactionCode\": { \r\n        \"Code\": \"FixedTermLoans\", \r\n        \"SubCode\": \"Fees(Generic)\"\r\n    }, \r\n    \"ProprietaryBankTransactionCode: { \r\n       \"Code\": \"DirectDebit\", \r\n       \"Issuer\": \"AlphaBank\" \r\n    }\r\n```\r\n\r\nWhen an Open Banking transaction is mapped into our standard transaction format,\r\nthese codes are included in the codes property of the transaction object:\r\n```json\r\n\"codes\": [\r\n          {\r\n             \"scheme\": \"OpenBanking\",\r\n             \"code\": \"FixedTermLoans\",\r\n             \"subCode\": \"Fees(Generic)\"\r\n          },\r\n          {\r\n             \"scheme\": \"AlphaBank\",\r\n             \"code\": \"DirectDebit\"\r\n          }\r\n\t   ]\r\n```\r\n\r\nCodes from other sources, such as Yodlee, are similarly mapped into the codes section.\r\n## Transaction Categorisations\r\n_Verdus optionally performs data enrichment by augmenting the raw transaction data with additional\r\ndata about the category of the transaction. The Transactions Model contains a **categorisations** property containing transaction categories.\r\n\r\nDepending upon the source of the data and the categorisation engines used, there may be multiple categories for a single transaction. For example:\r\n\r\n```json\r\n    \"categorisations\": [\r\n       {\r\n          \"scheme\": \"Yodlee\",\r\n          \"code\": \"Entertainment/Recreation\"\r\n       },\r\n       {\r\n          \"scheme\": \"Trusso\",\r\n          \"code\": \"EXP-B03\",\r\n          \"confidence\": 0.46,\r\n          \"name\": \"Bank Transfer\"\r\n       }\r\n    ]   \r\n```\r\n\r\n\r\n\r\n## Transaction Descriptions\r\nDepending upon the source of the data and the processing performed, a degree of enhancement and cleansing may be performed on the description field.  \r\n\r\nOften, description fields arrive from the third-party data sources in uppercase and with miscellaneous data attached such as merchant and other identifying codes.  \r\n\r\nWhere possible, Verdus strips these away and provides cleansed transaction descriptions in the descriptions collection of the transaction object:\r\n\r\n\r\n```json\r\n\"descriptions\": [\r\n      {\r\n          \"scheme\": \"YodleeOriginal\",\r\n          \"text\": \"Netflix NT346980277\"\r\n      },\r\n      {\r\n          \"scheme\": \"YodleeSimple\",\r\n          \"text\": \"Netflix\"\r\n      }\r\n   ]\r\n```\r\n\r\n\r\n# Metrics & Recurrences\r\nAs well as providing raw transaction data, the Transactions API also provides aggregated analysis data in the form of Recurrences and Metrics.\r\n\r\nRecurrences are transactions that happen with a degree of regularity on a Daily, Weekly, Fortnightly or Monthly basis.  Examples of recurring transactions are Bills, Mortgage Payments, Child Allowance Payments.  These transactions occur regularly, often around the same day of the month and are therefore examples of Recurrences.\r\n\r\nMetrics are aggregated data on income and expenditure.  Several metrics are returned by the Transactions API, defined as follows:   \r\n\r\n### List of Metrics\r\n\r\n\r\nMetric  | Description\r\n------------- | -------------\r\nExpenditureEssential |\tExpenditure on essential items: e.g. Food, Utility Bills, Transport\r\nExpenditureQualityOfLiving |\tExpenditure on non-essential items: e.g. Pub, Holidays, Shows, Theatre\r\nExpenditureCommitted |\tExpenditure on committed regular payments: Gym, Mobile Phone, Direct debits, Bills, Mortgage, Insurance\r\nExpenditureOther |\tMiscellaneous Expenses\r\nIncomeRegular |\tMonthly Salary Payment\r\nIncomeIrregular |\tIrregular Payments: Prizes, Pay for Odd Jobs, Monetary Gift/Loan\r\nIncomeDisposable |\tRemaining income after essential expenses deducted\r\nIncomeRemnant |\tRemaining income after all expenses deducted\r\n\r\nâ€ƒ\r\n",
    "title": "Runpath.Transactions",
    "version": "1.14"
  },
  "servers": [
    {
      "url": "https://cat.transactions.runpath.com/"
    }
  ],
  "paths": {
    "/owneditems/{ownedItemId}": {
      "delete": {
        "parameters": [
          {
            "description": "The identifier of the owned item",
            "in": "path",
            "name": "ownedItemId",
            "required": true,
            "schema": {
              "format": "int32",
              "type": "integer"
            }
          }
        ],
        "responses": {
          "204": {
            "description": "NoContent"
          },
          "401": {
            "description": "Unauthorized"
          },
          "403": {
            "description": "Forbidden"
          },
          "404": {
            "description": "Not Found"
          },
          "500": {
            "description": "Internal Server Error"
          }
        },
        "tags": [
          "OwnedItems"
        ],
        "operationId": "OwnedItems_DeleteByOwnedItemId",
        "summary": "Delete all transactions for an owned item"
      }
    },
    "/owneditems/{ownedItemId}/metrics": {
      "get": {
        "parameters": [
          {
            "description": "The identifier of the owned item",
            "in": "path",
            "name": "ownedItemId",
            "required": true,
            "schema": {
              "format": "int32",
              "type": "integer"
            }
          },
          {
            "description": "Filter transactions using OData syntax e.g. $filter=bookingDate ge 2017-01-01T23:59:59.99Z and bookingDate lt 2017-02-01T23:59:59.99Z",
            "in": "query",
            "name": "$filter",
            "required": false,
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "content": {
              "application/json": {
                "examples": {
                  "response": {
                    "value": {
                      "amount": 1265.54,
                      "name": "ExpenditureEssential"
                    }
                  }
                },
                "schema": {
                  "items": {
                    "$ref": "#/components/schemas/MetricsItem"
                  },
                  "type": "array"
                }
              },
              "text/json": {
                "schema": {
                  "items": {
                    "$ref": "#/components/schemas/MetricsItem"
                  },
                  "type": "array"
                }
              }
            },
            "description": "OK"
          },
          "401": {
            "description": "Unauthorized"
          },
          "403": {
            "description": "Forbidden"
          },
          "404": {
            "description": "Not Found"
          },
          "500": {
            "description": "Internal Server Error"
          }
        },
        "tags": [
          "OwnedItems"
        ],
        "operationId": "OwnedItems_GetMetricsByOwnedItemId",
        "summary": "Get metrics for an owned item"
      }
    },
    "/owneditems/{ownedItemId}/recurrences": {
      "get": {
        "parameters": [
          {
            "description": "The identifier of the owned item",
            "in": "path",
            "name": "ownedItemId",
            "required": true,
            "schema": {
              "format": "int32",
              "type": "integer"
            }
          }
        ],
        "responses": {
          "200": {
            "content": {
              "application/json": {
                "examples": {
                  "response": {
                    "value": {
                      "amount": 9.99,
                      "category": "TV Subscription",
                      "consistency": 1,
                      "day": 7,
                      "description": "Netflix Subscription",
                      "frequency": "Monthly",
                      "transactionIds": [
                        698225,
                        855565
                      ]
                    }
                  }
                },
                "schema": {
                  "items": {
                    "$ref": "#/components/schemas/Recurrence"
                  },
                  "type": "array"
                }
              },
              "text/json": {
                "schema": {
                  "items": {
                    "$ref": "#/components/schemas/Recurrence"
                  },
                  "type": "array"
                }
              }
            },
            "description": "OK"
          },
          "401": {
            "description": "Unauthorized"
          },
          "403": {
            "description": "Forbidden"
          },
          "404": {
            "description": "Not Found"
          },
          "500": {
            "description": "Internal Server Error"
          }
        },
        "tags": [
          "OwnedItems"
        ],
        "operationId": "OwnedItems_GetRecurrencesForOwnedItem",
        "summary": "Return a collection of recurrent transactions"
      }
    },
    "/owneditems/{ownedItemId}/transactions": {
      "get": {
        "parameters": [
          {
            "description": "The identifier of the owned item",
            "in": "path",
            "name": "ownedItemId",
            "required": true,
            "schema": {
              "format": "int32",
              "type": "integer"
            }
          },
          {
            "description": "Filter transactions using OData syntax e.g. $filter=bookingDate ge 2017-01-01T23:59:59.99Z and bookingDate lt 2017-02-01T23:59:59.99Z",
            "in": "query",
            "name": "$filter",
            "required": false,
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "content": {
              "application/json": {
                "examples": {
                  "response": {
                    "value": [
                      {
                        "address": {
                          "city": "London",
                          "country": "United Kingdom",
                          "latitude": 51.5074,
                          "line1": "20 Kensington High Street",
                          "longitude": 0.1278,
                          "postcode": "W8 5JH"
                        },
                        "amount": 9.99,
                        "balance": 1236.65,
                        "bookingDate": "2018-10-07T22:07:18.6749325+00:00",
                        "categorisations": [
                          {
                            "code": "EXP-G03",
                            "confidence": 0.9,
                            "scheme": "Trusso"
                          },
                          {
                            "code": "Entertainment/Recreation",
                            "confidence": 1,
                            "scheme": "Yodlee"
                          }
                        ],
                        "codes": [
                          {
                            "code": "IssuedCreditTransfer",
                            "scheme": "OpenBanking",
                            "subCode": "AutomaticTransfer"
                          },
                          {
                            "code": "DirectDebit",
                            "scheme": "AlphaBank"
                          }
                        ],
                        "createdDate": "0001-01-01T00:00:00+00:00",
                        "currency": "GBP",
                        "descriptions": [
                          {
                            "scheme": "YodleeOriginal",
                            "text": "Netflix NT346980277"
                          },
                          {
                            "scheme": "YodleeSimple",
                            "text": "Netflix"
                          }
                        ],
                        "id": 556665,
                        "merchant": {
                          "isoCode": "69865",
                          "name": "Netflix"
                        }
                      }
                    ]
                  }
                },
                "schema": {
                  "items": {
                    "$ref": "#/components/schemas/Transaction"
                  },
                  "type": "array"
                }
              },
              "text/json": {
                "schema": {
                  "items": {
                    "$ref": "#/components/schemas/Transaction"
                  },
                  "type": "array"
                }
              }
            },
            "description": "OK"
          },
          "401": {
            "description": "Unauthorized"
          },
          "403": {
            "description": "Forbidden"
          },
          "404": {
            "description": "Not Found"
          },
          "500": {
            "description": "Internal Server Error"
          }
        },
        "tags": [
          "OwnedItems"
        ],
        "operationId": "OwnedItems_GetTransactionsByOwnedItemId",
        "summary": "Get collection of transactions for an owned item"
      },
      "post": {
        "parameters": [
          {
            "description": "The identifier of the owned item",
            "in": "path",
            "name": "ownedItemId",
            "required": true,
            "schema": {
              "format": "int32",
              "type": "integer"
            }
          }
        ],
        "responses": {
          "204": {
            "description": "NoContent"
          },
          "400": {
            "description": "BadRequest"
          },
          "401": {
            "description": "Unauthorized"
          },
          "403": {
            "description": "Forbidden"
          },
          "404": {
            "description": "Not Found"
          },
          "422": {
            "description": "Unprocessable Entity"
          },
          "500": {
            "description": "Internal Server Error"
          }
        },
        "tags": [
          "OwnedItems"
        ],
        "operationId": "OwnedItems_AddTransactionsToOwnedItem",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "items": {
                  "$ref": "#/components/schemas/Transaction"
                },
                "type": "array"
              }
            },
            "text/json": {
              "schema": {
                "items": {
                  "$ref": "#/components/schemas/Transaction"
                },
                "type": "array"
              }
            }
          },
          "description": "The collection of transactions",
          "required": true
        },
        "summary": "Add a collection of transactions for an owned item"
      },
      "put": {
        "parameters": [
          {
            "description": "The identifier of the owned item",
            "in": "path",
            "name": "ownedItemId",
            "required": true,
            "schema": {
              "format": "int32",
              "type": "integer"
            }
          }
        ],
        "responses": {
          "204": {
            "description": "NoContent"
          },
          "400": {
            "description": "BadRequest"
          },
          "401": {
            "description": "Unauthorized"
          },
          "403": {
            "description": "Forbidden"
          },
          "404": {
            "description": "Not Found"
          },
          "422": {
            "description": "Unprocessable Entity"
          },
          "500": {
            "description": "Internal Server Error"
          }
        },
        "tags": [
          "OwnedItems"
        ],
        "operationId": "OwnedItems_UpsertTransactionsForOwnedItem",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "items": {
                  "$ref": "#/components/schemas/Transaction"
                },
                "type": "array"
              }
            },
            "text/json": {
              "schema": {
                "items": {
                  "$ref": "#/components/schemas/Transaction"
                },
                "type": "array"
              }
            }
          },
          "description": "The collection of transactions",
          "required": true
        },
        "summary": "Upserts a collection of transactions, creates new transactions and updates those that already exist"
      }
    },
    "/parties/{partyId}/metrics": {
      "get": {
        "parameters": [
          {
            "in": "path",
            "name": "partyId",
            "required": true,
            "schema": {
              "format": "int32",
              "type": "integer"
            }
          },
          {
            "description": "Filter transactions using OData syntax e.g. $filter=bookingDate ge 2017-01-01T23:59:59.99Z and bookingDate lt 2017-02-01T23:59:59.99Z",
            "in": "query",
            "name": "$filter",
            "required": false,
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "content": {
              "application/json": {
                "examples": {
                  "response": {
                    "value": {
                      "amount": 1265.54,
                      "name": "ExpenditureEssential"
                    }
                  }
                },
                "schema": {
                  "items": {
                    "$ref": "#/components/schemas/MetricsItem"
                  },
                  "type": "array"
                }
              },
              "text/json": {
                "schema": {
                  "items": {
                    "$ref": "#/components/schemas/MetricsItem"
                  },
                  "type": "array"
                }
              }
            },
            "description": "OK"
          },
          "401": {
            "description": "Unauthorized"
          },
          "403": {
            "description": "Forbidden"
          },
          "404": {
            "description": "Not Found"
          },
          "500": {
            "description": "Internal Server Error"
          }
        },
        "tags": [
          "Parties"
        ],
        "operationId": "Parties_GetMetricsByPartyId",
        "summary": "Get metrics for an owned item"
      }
    },
    "/transactions": {
      "post": {
        "responses": {
          "201": {
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Transaction"
                }
              },
              "text/json": {
                "schema": {
                  "$ref": "#/components/schemas/Transaction"
                }
              }
            },
            "description": "Created"
          },
          "401": {
            "description": "Unauthorized"
          },
          "403": {
            "description": "Forbidden"
          },
          "404": {
            "description": "Not Found"
          },
          "422": {
            "description": "Unprocessable Entity"
          },
          "500": {
            "description": "Internal Server Error"
          }
        },
        "tags": [
          "Transactions"
        ],
        "operationId": "Transactions_Create",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/Transaction"
              }
            },
            "text/json": {
              "schema": {
                "$ref": "#/components/schemas/Transaction"
              }
            }
          },
          "description": "The new transaction",
          "required": true
        },
        "summary": "Add a new transaction"
      }
    },
    "/transactions/{id}": {
      "delete": {
        "parameters": [
          {
            "description": "The transaction identifier",
            "in": "path",
            "name": "id",
            "required": true,
            "schema": {
              "format": "int64",
              "type": "integer"
            }
          }
        ],
        "responses": {
          "204": {
            "description": "NoContent"
          },
          "401": {
            "description": "Unauthorized"
          },
          "403": {
            "description": "Forbidden"
          },
          "404": {
            "description": "Not Found"
          },
          "500": {
            "description": "Internal Server Error"
          }
        },
        "tags": [
          "Transactions"
        ],
        "operationId": "Transactions_Delete",
        "summary": "Delete an identified transaction"
      },
      "get": {
        "parameters": [
          {
            "description": "The transaction identifier",
            "in": "path",
            "name": "id",
            "required": true,
            "schema": {
              "format": "int64",
              "type": "integer"
            }
          }
        ],
        "responses": {
          "200": {
            "content": {
              "application/json": {
                "examples": {
                  "response": {
                    "value": {
                      "address": {
                        "city": "London",
                        "country": "United Kingdom",
                        "latitude": 51.5074,
                        "line1": "20 Kensington High Street",
                        "longitude": 0.1278,
                        "postcode": "W8 5JH"
                      },
                      "amount": 9.99,
                      "balance": 1236.65,
                      "bookingDate": "2018-10-07T22:07:18.6905359+00:00",
                      "categorisations": [
                        {
                          "code": "EXP-G03",
                          "confidence": 0.9,
                          "scheme": "Trusso"
                        },
                        {
                          "code": "Entertainment/Recreation",
                          "confidence": 1,
                          "scheme": "Yodlee"
                        }
                      ],
                      "codes": [
                        {
                          "code": "IssuedCreditTransfer",
                          "scheme": "OpenBanking",
                          "subCode": "AutomaticTransfer"
                        },
                        {
                          "code": "DirectDebit",
                          "scheme": "AlphaBank"
                        }
                      ],
                      "createdDate": "0001-01-01T00:00:00+00:00",
                      "currency": "GBP",
                      "descriptions": [
                        {
                          "scheme": "YodleeOriginal",
                          "text": "Netflix NT346980277"
                        },
                        {
                          "scheme": "YodleeSimple",
                          "text": "Netflix"
                        }
                      ],
                      "id": 556665,
                      "merchant": {
                        "isoCode": "69865",
                        "name": "Netflix"
                      }
                    }
                  }
                },
                "schema": {
                  "$ref": "#/components/schemas/Transaction"
                }
              },
              "text/json": {
                "schema": {
                  "$ref": "#/components/schemas/Transaction"
                }
              }
            },
            "description": "OK"
          },
          "201": {
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Transaction"
                }
              },
              "text/json": {
                "schema": {
                  "$ref": "#/components/schemas/Transaction"
                }
              }
            },
            "description": "Created"
          },
          "401": {
            "description": "Unauthorized"
          },
          "403": {
            "description": "Forbidden"
          },
          "404": {
            "description": "Not Found"
          },
          "500": {
            "description": "Internal Server Error"
          }
        },
        "tags": [
          "Transactions"
        ],
        "operationId": "Transactions_GetById",
        "summary": "Get an identified transaction"
      },
      "put": {
        "parameters": [
          {
            "description": "The transaction identifier",
            "in": "path",
            "name": "id",
            "required": true,
            "schema": {
              "format": "int64",
              "type": "integer"
            }
          }
        ],
        "responses": {
          "200": {
            "content": {
              "application/json": {
                "schema": {
                  "type": "object"
                }
              },
              "text/json": {
                "schema": {
                  "type": "object"
                }
              }
            },
            "description": "OK"
          },
          "401": {
            "description": "Unauthorized"
          },
          "403": {
            "description": "Forbidden"
          },
          "404": {
            "description": "Not Found"
          },
          "422": {
            "description": "Unprocessable Entity"
          },
          "500": {
            "description": "Internal Server Error"
          }
        },
        "tags": [
          "Transactions"
        ],
        "operationId": "Transactions_Update",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/Transaction"
              }
            },
            "text/json": {
              "schema": {
                "$ref": "#/components/schemas/Transaction"
              }
            }
          },
          "description": "The updated transaction state",
          "required": true
        },
        "summary": "Update an identified transaction"
      }
    }
  },
  "components": {
    "requestBodies": {
      "TransactionArray": {
        "content": {
          "application/json": {
            "schema": {
              "items": {
                "$ref": "#/components/schemas/Transaction"
              },
              "type": "array"
            }
          },
          "text/json": {
            "schema": {
              "items": {
                "$ref": "#/components/schemas/Transaction"
              },
              "type": "array"
            }
          }
        },
        "description": "The collection of transactions",
        "required": true
      }
    },
    "schemas": {
      "Address": {
        "description": "A representation of an Address",
        "properties": {
          "city": {
            "description": "City",
            "maxLength": 100,
            "minLength": 0,
            "type": "string"
          },
          "country": {
            "description": "Country",
            "maxLength": 100,
            "minLength": 0,
            "type": "string"
          },
          "latitude": {
            "description": "The latitude of the coordinate",
            "format": "double",
            "type": "number"
          },
          "line1": {
            "description": "The first line of the address",
            "maxLength": 100,
            "minLength": 0,
            "type": "string"
          },
          "longitude": {
            "description": "The longitude of the coordinate",
            "format": "double",
            "type": "number"
          },
          "postcode": {
            "description": "Postcode",
            "maxLength": 50,
            "minLength": 0,
            "type": "string"
          }
        },
        "type": "object"
      },
      "Categorisation": {
        "description": "A categorisation of a transaction",
        "properties": {
          "code": {
            "description": "The code value from the given scheme",
            "maxLength": 50,
            "minLength": 0,
            "type": "string"
          },
          "confidence": {
            "description": "The confidence level for the categorisation",
            "format": "double",
            "type": "number"
          },
          "name": {
            "maxLength": 50,
            "minLength": 0,
            "type": "string"
          },
          "scheme": {
            "description": "The scheme of the categorisation",
            "maxLength": 50,
            "minLength": 0,
            "type": "string"
          }
        },
        "type": "object"
      },
      "Description": {
        "description": "A description of a transaction",
        "properties": {
          "scheme": {
            "description": "The source of the description",
            "maxLength": 50,
            "minLength": 0,
            "type": "string"
          },
          "text": {
            "description": "The textual description",
            "maxLength": 500,
            "minLength": 0,
            "type": "string"
          }
        },
        "type": "object"
      },
      "Merchant": {
        "description": "A merchant of a transaction",
        "properties": {
          "isoCode": {
            "description": "The ISO 18245 code",
            "maxLength": 50,
            "minLength": 0,
            "type": "string"
          },
          "name": {
            "description": "The name",
            "maxLength": 100,
            "minLength": 0,
            "type": "string"
          }
        },
        "type": "object"
      },
      "MetricsItem": {
        "description": "A representation of a Metric Datum",
        "properties": {
          "amount": {
            "description": "The amount",
            "format": "double",
            "type": "number"
          },
          "name": {
            "description": "The Name",
            "maxLength": 50,
            "minLength": 0,
            "type": "string"
          }
        },
        "type": "object"
      },
      "Recurrence": {
        "description": "A recurring series of transactions",
        "properties": {
          "amount": {
            "description": "The monetary value of the recurring transaction",
            "format": "double",
            "type": "number"
          },
          "category": {
            "description": "The category of the recurring transaction",
            "maxLength": 50,
            "minLength": 0,
            "type": "string"
          },
          "consistency": {
            "description": "The level of consistency of the recurrence",
            "format": "double",
            "type": "number"
          },
          "day": {
            "description": "The day of the month the transaction recurs",
            "format": "int32",
            "type": "integer"
          },
          "description": {
            "description": "The description of the recurring transaction",
            "maxLength": 500,
            "minLength": 0,
            "type": "string"
          },
          "frequency": {
            "description": "The recurrence frequency",
            "enum": [
              "Daily",
              "Weekly",
              "Fortnightly",
              "Monthly",
              "Inconclusive"
            ],
            "type": "string"
          },
          "transactionIds": {
            "description": "The identifiers of the recurring transactions",
            "items": {
              "format": "int64",
              "type": "integer"
            },
            "type": "array"
          }
        },
        "type": "object"
      },
      "Transaction": {
        "description": "A financial transaction",
        "example": {
          "address": {
            "city": "London",
            "country": "United Kingdom",
            "latitude": 51.5074,
            "line1": "20 Kensington High Street",
            "longitude": 0.1278,
            "postcode": "W8 5JH"
          },
          "amount": 9.99,
          "balance": 1236.65,
          "bookingDate": "2018-10-07T22:07:18.6905359+00:00",
          "categorisations": [
            {
              "code": "EXP-G03",
              "confidence": 0.9,
              "scheme": "Trusso"
            },
            {
              "code": "Entertainment/Recreation",
              "confidence": 1,
              "scheme": "Yodlee"
            }
          ],
          "codes": [
            {
              "code": "IssuedCreditTransfer",
              "scheme": "OpenBanking",
              "subCode": "AutomaticTransfer"
            },
            {
              "code": "DirectDebit",
              "scheme": "AlphaBank"
            }
          ],
          "createdDate": "0001-01-01T00:00:00+00:00",
          "currency": "GBP",
          "descriptions": [
            {
              "scheme": "YodleeOriginal",
              "text": "Netflix NT346980277"
            },
            {
              "scheme": "YodleeSimple",
              "text": "Netflix"
            }
          ],
          "id": 556665,
          "merchant": {
            "isoCode": "69865",
            "name": "Netflix"
          }
        },
        "properties": {
          "address": {
            "$ref": "#/components/schemas/Address",
            "description": "The address location"
          },
          "amount": {
            "description": "The monetary amount. For a debit the amount is a negative value, whilst a credit is a positive value. \r\nFor example, the purchase of a coffee would be -2.75 whilst a salary payment would be 3531.75",
            "format": "double",
            "type": "number"
          },
          "balance": {
            "description": "The current balance",
            "format": "double",
            "type": "number"
          },
          "bookingDate": {
            "description": "The date when the transaction was posted to the account",
            "example": "2018-10-10T22:07:18.2530304+00:00",
            "format": "date-time",
            "type": "string"
          },
          "categorisations": {
            "description": "A collection of categorisations",
            "items": {
              "$ref": "#/components/schemas/Categorisation"
            },
            "type": "array"
          },
          "codes": {
            "description": "A collection of bank codes",
            "items": {
              "$ref": "#/components/schemas/TransactionCode"
            },
            "type": "array"
          },
          "createdDate": {
            "description": "The created date of the transaction representation",
            "example": "2018-10-10T22:07:18.2530304+00:00",
            "format": "date-time",
            "type": "string"
          },
          "currency": {
            "description": "The ISO 4217 currency code for the amount and the balances",
            "maxLength": 3,
            "minLength": 0,
            "type": "string"
          },
          "descriptions": {
            "description": "A collection of descriptions",
            "items": {
              "$ref": "#/components/schemas/Description"
            },
            "type": "array"
          },
          "id": {
            "description": "The identifier of the transaction",
            "format": "int64",
            "type": "integer"
          },
          "merchant": {
            "$ref": "#/components/schemas/Merchant",
            "description": "The merchant details"
          },
          "ownedItemId": {
            "description": "The identifier of the containing ownedItem",
            "format": "int32",
            "type": "integer"
          },
          "reference": {
            "description": "A unique reference for the transaction",
            "maxLength": 50,
            "minLength": 0,
            "type": "string"
          },
          "status": {
            "description": "The current status",
            "enum": [
              "Booked",
              "Pending"
            ],
            "type": "string"
          },
          "transactionId": {
            "description": "The unique identifier for the transaction within an servicing institution e.g. TransactionId from Open Banking",
            "maxLength": 100,
            "minLength": 0,
            "type": "string"
          },
          "valueDate": {
            "description": "Date and time when assets become available to the account in case of a credit, or cease to be available in case of a debit.",
            "example": "2018-10-10T22:07:18.2530304+00:00",
            "format": "date-time",
            "type": "string"
          }
        },
        "required": [
          "ownedItemId",
          "status"
        ],
        "type": "object"
      },
      "TransactionCode": {
        "description": "A standardised code",
        "properties": {
          "code": {
            "description": "The code",
            "maxLength": 100,
            "minLength": 0,
            "type": "string"
          },
          "scheme": {
            "description": "The scheme of the code list",
            "maxLength": 50,
            "minLength": 0,
            "type": "string"
          },
          "subCode": {
            "description": "The sub-code within the code",
            "maxLength": 100,
            "minLength": 0,
            "type": "string"
          }
        },
        "required": [
          "scheme",
          "code"
        ],
        "type": "object"
      }
    }
  }
}
